---
ip: "192.168.33.31"
cpus: 2
memory: ~

authorize: ~/.ssh/id_rsa.pub

keys:
  - ~/.ssh/id_rsa

ports:
    http: 8000
    https: 4430

folders:
    - map: ~/Sites/
      to: /var/www/html/
      with: ~
      options: ['dmode=777,fmode=777']
